/** Generated by YAKINDU Statechart Tools code generator. */


#include "../Inc/sc_types.h"

#include "../Inc/blinky.h"
#include "../Inc/blinky_required.h"

/*! \file Implementation of the state machine 'blinky'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_LEDs_off(Blinky* handle);
static void enact_main_region_LEDs_on(Blinky* handle);
static void exact_main_region_LEDs_off(Blinky* handle);
static void exact_main_region_LEDs_on(Blinky* handle);
static void enseq_main_region_LEDs_off_default(Blinky* handle);
static void enseq_main_region_LEDs_on_default(Blinky* handle);
static void enseq_main_region_default(Blinky* handle);
static void exseq_main_region_LEDs_off(Blinky* handle);
static void exseq_main_region_LEDs_on(Blinky* handle);
static void exseq_main_region(Blinky* handle);
static void react_main_region__entry_Default(Blinky* handle);

/*! State machine reactions. */
static sc_integer react(Blinky* handle, const sc_integer transitioned_before);

/*! The reactions of state LEDs off. */
static sc_integer main_region_LEDs_off_react(Blinky* handle, const sc_integer transitioned_before);

/*! The reactions of state LEDs on. */
static sc_integer main_region_LEDs_on_react(Blinky* handle, const sc_integer transitioned_before);


static void clear_in_events(Blinky* handle);

static void micro_step(Blinky* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Blinky* handle);



static void blinky_eventqueue_init(blinky_eventqueue * eq, blinky_event *buffer, sc_integer capacity);
static sc_integer blinky_eventqueue_size(blinky_eventqueue * eq);
static void blinky_event_init(blinky_event * ev, BlinkyEventID name);
static blinky_event blinky_eventqueue_pop(blinky_eventqueue * eq);
static sc_boolean blinky_eventqueue_push(blinky_eventqueue * eq, blinky_event ev);
static void blinky_add_event_to_queue(blinky_eventqueue * eq, BlinkyEventID name);
static void blinky_dispatch_event(Blinky* handle, const blinky_event * event);
static blinky_event blinky_get_next_event(Blinky* handle);
static void blinky_dispatch_next_event(Blinky* handle);
static BlinkyEventID blinky_get_timed_event_name(Blinky* handle, sc_eventid evid);


void blinky_init(Blinky* handle)
{
	sc_integer i;
	
	for (i = 0; i < BLINKY_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Blinky_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart blinky */
	handle->iface.main = SCT_MAIN;
	
	handle->isExecuting = bool_false;
	blinky_eventqueue_init(&handle->in_event_queue, handle->in_buffer, BLINKY_IN_EVENTQUEUE_BUFFERSIZE);
}

void blinky_enter(Blinky* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart blinky */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void blinky_exit(Blinky* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart blinky */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean blinky_is_active(const Blinky* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < BLINKY_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Blinky_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean blinky_is_final(const Blinky* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void blinky_raise_time_event(Blinky* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(BlinkyTimeEvents))
	{
		blinky_add_event_to_queue(&(handle->in_event_queue), blinky_get_timed_event_name(handle, evid));
		run_cycle(handle);
	}
}

sc_boolean blinky_is_state_active(const Blinky* handle, BlinkyStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Blinky_main_region_LEDs_off :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINKY_MAIN_REGION_LEDS_OFF] == Blinky_main_region_LEDs_off
			);
			break;
		case Blinky_main_region_LEDs_on :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINKY_MAIN_REGION_LEDS_ON] == Blinky_main_region_LEDs_on
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clear_in_events(Blinky* handle)
{
	handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised = bool_false;
	handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised = bool_false;
}

static void micro_step(Blinky* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Blinky_main_region_LEDs_off :
		{
			main_region_LEDs_off_react(handle, -1);
			break;
		}
		case Blinky_main_region_LEDs_on :
		{
			main_region_LEDs_on_react(handle, -1);
			break;
		}
		default: break;
	}
}

static void run_cycle(Blinky* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	blinky_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
		blinky_dispatch_next_event(handle);
	} while ((handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised == bool_true) || (handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised == bool_true));
	handle->isExecuting = bool_false;
}




int8_t blinky_get_main(const Blinky* handle)
{
	return handle->iface.main;
}
void blinky_set_main(Blinky* handle, int8_t value)
{
	handle->iface.main = value;
}

/* implementations of all internal functions */

/* Entry action for state 'LEDs off'. */
static void enact_main_region_LEDs_off(Blinky* handle)
{
	/* Entry action for state 'LEDs off'. */
	blinky_set_timer(handle, (sc_eventid) &(handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised) , (1 * 1000), bool_false);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_RESET);
}

/* Entry action for state 'LEDs on'. */
static void enact_main_region_LEDs_on(Blinky* handle)
{
	/* Entry action for state 'LEDs on'. */
	blinky_set_timer(handle, (sc_eventid) &(handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised) , (1 * 1000), bool_false);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_13, GPIO_PIN_SET);
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_14, GPIO_PIN_SET);
	HAL_GPIO_WritePin(GPIOC, GPIO_PIN_14, GPIO_PIN_SET);
}

/* Exit action for state 'LEDs off'. */
static void exact_main_region_LEDs_off(Blinky* handle)
{
	/* Exit action for state 'LEDs off'. */
	blinky_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised) );		
}

/* Exit action for state 'LEDs on'. */
static void exact_main_region_LEDs_on(Blinky* handle)
{
	/* Exit action for state 'LEDs on'. */
	blinky_unset_timer(handle, (sc_eventid) &(handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised) );		
}

/* 'default' enter sequence for state LEDs off */
static void enseq_main_region_LEDs_off_default(Blinky* handle)
{
	/* 'default' enter sequence for state LEDs off */
	enact_main_region_LEDs_off(handle);
	handle->stateConfVector[0] = Blinky_main_region_LEDs_off;
}

/* 'default' enter sequence for state LEDs on */
static void enseq_main_region_LEDs_on_default(Blinky* handle)
{
	/* 'default' enter sequence for state LEDs on */
	enact_main_region_LEDs_on(handle);
	handle->stateConfVector[0] = Blinky_main_region_LEDs_on;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Blinky* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state LEDs off */
static void exseq_main_region_LEDs_off(Blinky* handle)
{
	/* Default exit sequence for state LEDs off */
	handle->stateConfVector[0] = Blinky_last_state;
	exact_main_region_LEDs_off(handle);
}

/* Default exit sequence for state LEDs on */
static void exseq_main_region_LEDs_on(Blinky* handle)
{
	/* Default exit sequence for state LEDs on */
	handle->stateConfVector[0] = Blinky_last_state;
	exact_main_region_LEDs_on(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Blinky* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of blinky.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Blinky_main_region_LEDs_off :
		{
			exseq_main_region_LEDs_off(handle);
			break;
		}
		case Blinky_main_region_LEDs_on :
		{
			exseq_main_region_LEDs_on(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Blinky* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_LEDs_off_default(handle);
}


static sc_integer react(Blinky* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_LEDs_off_react(Blinky* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LEDs off. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised == bool_true)
		{ 
			exseq_main_region_LEDs_off(handle);
			handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised = bool_false;
			enseq_main_region_LEDs_on_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_LEDs_on_react(Blinky* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LEDs on. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised == bool_true)
		{ 
			exseq_main_region_LEDs_on(handle);
			handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised = bool_false;
			enseq_main_region_LEDs_off_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}




static void blinky_eventqueue_init(blinky_eventqueue * eq, blinky_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer blinky_eventqueue_size(blinky_eventqueue * eq)
{
	return eq->size;
}

static blinky_event blinky_eventqueue_pop(blinky_eventqueue * eq)
{
	blinky_event event;
	if(blinky_eventqueue_size(eq) <= 0) {
		blinky_event_init(&event, Blinky_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean blinky_eventqueue_push(blinky_eventqueue * eq, blinky_event ev)
{
	if(blinky_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void blinky_event_init(blinky_event * ev, BlinkyEventID name)
{
	ev->name = name;
}

static void blinky_add_event_to_queue(blinky_eventqueue * eq, BlinkyEventID name)
{
	blinky_event event;
	blinky_event_init(&event, name);
	blinky_eventqueue_push(eq, event);
}

static void blinky_dispatch_event(Blinky* handle, const blinky_event * event) {
	switch(event->name) {
		case Blinky_blinky_main_region_LEDs_off_time_event_0:
		{
			handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised = bool_true;
			break;
		}
		case Blinky_blinky_main_region_LEDs_on_time_event_0:
		{
			handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static blinky_event blinky_get_next_event(Blinky* handle)
{
	blinky_event next_event;
	blinky_event_init(&next_event, Blinky_invalid_event);
	if(blinky_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = blinky_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void blinky_dispatch_next_event(Blinky* handle)
{
	blinky_event nextEvent;
	nextEvent = blinky_get_next_event(handle);
	blinky_dispatch_event(handle, &nextEvent);
}

static BlinkyEventID blinky_get_timed_event_name(Blinky* handle, sc_eventid evid)
{
	if(evid == &handle->timeEvents.blinky_main_region_LEDs_off_tev0_raised) {
		return Blinky_blinky_main_region_LEDs_off_time_event_0;
	}
	if(evid == &handle->timeEvents.blinky_main_region_LEDs_on_tev0_raised) {
		return Blinky_blinky_main_region_LEDs_on_time_event_0;
	}
	return Blinky_invalid_event;
}

